# Generated by Django 4.0.6 on 2022-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralizedHitsSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(default=None)),
                ('source', models.CharField(max_length=255)),
                ('source_id', models.BigIntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('doi', models.CharField(default=None, max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
