# Generated by Django 4.0.6 on 2022-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
