# Generated by Django 4.0.6 on 2022-10-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_generalizedhitssearch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
