# Generated by Django 4.0.6 on 2022-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_generalizedhitssearch_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='doi',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='language',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
