# Generated by Django 4.0.6 on 2022-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_generalizedhitssearch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='publication_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
