# Generated by Django 4.0.6 on 2022-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_generalizedhitssearch_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='access_right',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='original_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
