# Generated by Django 4.0.6 on 2022-10-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_generalizedhitssearch_citations_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
