# Generated by Django 4.0.6 on 2022-10-26 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_generalizedhitssearch_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.TextField(default=None)),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='source_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=None, size=50),
        ),
    ]
