# Generated by Django 4.0.6 on 2022-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_generalizedhitssearch_source_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='publication_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
