# Generated by Django 4.0.6 on 2022-10-26 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_alter_generalizedhitssearch_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
