# Generated by Django 4.0.6 on 2022-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_generalizedhitssearch_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ManyToManyField(to='search.hitauthor'),
        ),
        migrations.AlterField(
            model_name='hitauthor',
            name='affiliation',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='hitauthor',
            name='name',
            field=models.TextField(blank=True, default=None),
        ),
    ]
