# Generated by Django 4.0.6 on 2022-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_generalizedhitssearch_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, to='search.hitauthor'),
        ),
    ]
