# Generated by Django 4.0.6 on 2022-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_alter_generalizedhitssearch_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ManyToManyField(to='search.hitauthor'),
        ),
    ]
