# Generated by Django 4.0.6 on 2022-10-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_alter_generalizedhitssearch_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitauthor',
            name='affiliation',
            field=models.TextField(default=None, null=True),
        ),
    ]
