# Generated by Django 4.0.6 on 2022-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_alter_hitauthor_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='hits_list', to='search.hitauthor'),
        ),
    ]
