# Generated by Django 4.0.6 on 2022-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_generalizedhitssearch_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
