# Generated by Django 4.0.6 on 2022-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_alter_generalizedhitssearch_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalizedhitssearch',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
