# Generated by Django 4.0.6 on 2022-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_alter_generalizedhitssearch_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(blank=True, max_length=512, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files_list', to='search.file'),
        ),
    ]
