# Generated by Django 4.0.6 on 2022-10-30 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_file_creation_date_hitauthor_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='issn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None),
        ),
    ]
