# Generated by Django 4.0.6 on 2022-10-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_generalizedhitssearch_issn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalizedhitssearch',
            old_name='issn',
            new_name='related_issn',
        ),
    ]
