# Generated by Django 4.0.6 on 2022-10-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_relatedidentifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='authors',
        ),
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='hits_list', to='search.hitauthor'),
            preserve_default=False,
        ),
    ]
