# Generated by Django 4.0.6 on 2022-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_remove_generalizedhitssearch_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='authors',
        ),
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='hits_list', to='search.hitauthor'),
        ),
    ]
