# Generated by Django 4.0.6 on 2022-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_alter_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalizedhitssearch',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
