# Generated by Django 4.0.6 on 2022-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0036_generalizedhitssearch_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='query',
        ),
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='user',
        ),
    ]
