# Generated by Django 4.0.6 on 2022-12-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0037_queryhit_remove_generalizedhitssearch_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='hit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='search.generalizedhitssearch'),
            preserve_default=False,
        ),
    ]
