# Generated by Django 4.0.6 on 2022-12-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_remove_generalizedhitssearch_files_file_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalizedhitssearch',
            name='favourite',
        ),
        migrations.AlterField(
            model_name='file',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='search.generalizedhitssearch'),
        ),
    ]
