# Generated by Django 4.0.6 on 2022-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecord',
            name='source',
            field=models.CharField(default='zenodo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriterecord',
            name='source_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
