# Generated by Django 4.0.6 on 2022-11-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_alter_file_link'),
        ('favorite_records', '0002_favoriterecord_source_favoriterecord_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecord',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='favoriterecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='favoriterecord',
            name='source_id',
        ),
        migrations.AddField(
            model_name='favoriterecord',
            name='record',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='record', to='search.generalizedhitssearch'),
            preserve_default=False,
        ),
    ]
