# Generated by Django 4.0.6 on 2022-12-22 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_remove_generalizedhitssearch_favourite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorite_records', '0003_remove_favoriterecord_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='search.generalizedhitssearch'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
