import logging
import re

from django.conf import settings


# from keybert import KeyBERT
from apps.site.favorite_records.models import FavoriteRecord

logger = logging.getLogger('__name__')


class BaseSearch:
    def __init__(self):
        self.zenodo_access_token = settings.ZENODO_ACCESS_TOKEN
        self.size = 100
        # self.kw_model = KeyBERT()
        # self.opencitations_api = OpencitationsAPI()

    @staticmethod
    def _remove_tags(text):
        """ remove html tags from hit description """
        tag_re = re.compile(r'<[^>]+>')
        return tag_re.sub('', text)

    @staticmethod
    def record_is_favourite(user: int, source: str, id=int):
        records = FavoriteRecord.objects.filter(user=user)
        logger.info(records)
        for record in records:
            if record.record.source == source and record.record.source_id == id:
                return True
        return False

    # def _get_autogenerated_keywords(self, text):
    #     keywords = self.kw_model.extract_keywords(text)
    #     return [key[0] for key in keywords]
