import re

from django.conf import settings
# from keybert import KeyBERT


class BaseSearch:
    def __init__(self):
        self.zenodo_access_token = settings.ZENODO_ACCESS_TOKEN
        self.size = 100
        # self.kw_model = KeyBERT()
        # self.opencitations_api = OpencitationsAPI()

    @staticmethod
    def _remove_tags(text):
        """ remove html tags from hit description """
        tag_re = re.compile(r'<[^>]+>')
        return tag_re.sub('', text)

    # def _get_autogenerated_keywords(self, text):
    #     keywords = self.kw_model.extract_keywords(text)
    #     return [key[0] for key in keywords]


