import logging
from typing import List

from django.conf import settings

from apps.search.api import celery_async_requests
from apps.search.api.base_search import BaseSearch
from apps.search.models import GeneralizedHit, Author, GeneralizedHitsSearch, HitAuthor

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


class Core(BaseSearch):

    def __init__(self):
        super().__init__()
        self.access_token = settings.CORE_ACCESS_TOKEN
        self.size = 50

    def _get_core_async_tasks(self, query: str, records_per_query: int = 50):
        headers = {'Authorization': f'Bearer {self.access_token}'}
        async_tasks = []
        body = {'q': query,
                'offset': 0,
                'limit': records_per_query}
        async_tasks.append(celery_async_requests.post.delay(url='https://api.core.ac.uk/v3/search/works',
                                                                headers=headers, body=body))

        return async_tasks

    def _parse_one_core_hit(self, hit_json, query: str) -> GeneralizedHit:  # TODO: access_right

        hit = GeneralizedHitsSearch()
        hit.query = query
        hit.source = 'core'
        hit.title = hit_json['title']
        hit.source_id = hit_json['id']

        if hit_json['abstract'] is not None:
            hit.description = self._remove_tags(hit_json['abstract']).replace('\n', ' ')
        else:
            hit.description = ''

        hit.publication_date = hit_json['publishedDate']
        display_links = list(filter(lambda x: x['type'] == 'display', hit_json['links']))

        if display_links:
            hit.original_url = display_links[0]['url']

        hit.doi = hit_json['doi']
        hit.access_right = 'open'
        if hit_json['language'] is not None:
            hit.language = hit_json['language']['code']

        if hit_json['citationCount'] is not None:
            hit.citations_number = hit_json['citationCount']

        if len(hit_json['documentType']) > 0:
            hit.type = hit_json['documentType']

        # hit.auto_generated_keywords = self._get_autogenerated_keywords(f'{hit.title}\n{hit.description}')
        hit.save()

        for hit_author in hit_json['authors']:
            author = HitAuthor()
            author.name = hit_author['name']
            author.save()

            hit.authors.add(author)
            # hit.authors.append(author)

        return hit

    def _get_core_hits(self, api_response, query: str) -> List[GeneralizedHit]:
        return [self._parse_one_core_hit(core_hit, query=query) for core_hit in api_response['results']]
